[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Adam K.", email = "arkelly111@gmail.com"},
]
dependencies = [
    "Django>=4.2.7",
    "pillow>=10.1.0",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

