[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Adam K.", email = "arkelly111@gmail.com"},
]
dependencies = [
    "django>=4.2.7",
    "pillow>=10.1.0",
    "django-stubs>=4.2.6",
    "django-allauth>=0.58.2",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

