services:
  - type: web
    plan: free
    name: misar_web
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn misar_web.asgi:application -k uvicorn.workers.UvicornWorker"
    disk:
    name: db.sqlite3
    mountPath: /src/misar_web/db.sqlite3
    sizeGB: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db.sqlite3
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
