# Generated by Django 4.2.7 on 2023-11-15 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="url",
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
