# Generated by Django 4.2.7 on 2023-11-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_siteinfo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="logo",
            field=models.ImageField(default="home/static/logo.jpg", upload_to=""),
        ),
    ]
