# Generated by Django 4.2.7 on 2023-11-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_siteinfo_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteinfo",
            name="logo",
            field=models.ImageField(default="./static/logo.jpg", upload_to=""),
        ),
    ]
