# Generated by Django 4.2.7 on 2023-11-16 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_siteinfo_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteinfo",
            name="logo",
        ),
        migrations.AddField(
            model_name="siteinfo",
            name="logo.jpg",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="images/"
            ),
            preserve_default=False,
        ),
    ]
