# Generated by Django 4.2.7 on 2023-11-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_remove_siteinfo_logo_siteinfo_logo_jpg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteinfo",
            name="logo.jpg",
            field=models.ImageField(
                default="home/images/logo.jpg", upload_to="images/"
            ),
        ),
    ]
