# Generated by Django 4.2.7 on 2023-11-16 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_siteinfo_logo_jpg"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siteinfo",
            old_name="logo.jpg",
            new_name="logo",
        ),
    ]
