# Generated by Django 4.2.7 on 2023-11-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_siteinfo_dispatch_number_siteinfo_mission_statement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteinfo",
            name="logo",
            field=models.ImageField(upload_to="static/images"),
        ),
    ]
