# Generated by Django 4.2.7 on 2023-11-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_alter_siteinfo_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteinfo",
            name="logo",
            field=models.ImageField(upload_to="home/static/images/"),
        ),
    ]
