# Generated by Django 4.2.7 on 2023-11-19 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_alter_siteinfo_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="home_page_image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="home/files/images"
            ),
            preserve_default=False,
        ),
    ]
