# Generated by Django 4.2.7 on 2023-11-21 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_siteinfo_alternate_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="donation_link",
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
