# Generated by Django 4.2.7 on 2023-11-25 04:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_siteinfo_donation_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteinfo",
            options={"verbose_name_plural": "information"},
        ),
    ]
