# Generated by Django 4.2.7 on 2023-11-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_alter_siteinfo_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="get_involved_blob",
            field=models.TextField(blank=True, null=True),
        ),
    ]
