# Generated by Django 4.2.7 on 2023-11-30 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0024_siteinfo_get_involved_blob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteinfo",
            name="get_involved_blob",
        ),
    ]
