# Generated by Django 4.2.7 on 2023-12-03 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_remove_siteinfo_get_involved_blob"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="mailing_address",
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="siteinfo",
            name="team_email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
