# Generated by Django 4.2.7 on 2023-12-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0027_siteinfo_team_goals"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamGoals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_goal", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "team_goals",
            },
        ),
        migrations.RemoveField(
            model_name="siteinfo",
            name="team_goals",
        ),
    ]
