# Generated by Django 4.2.7 on 2023-12-04 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0028_teamgoals_remove_siteinfo_team_goals"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teamgoals",
            options={"verbose_name_plural": "Team Goals"},
        ),
    ]
