# Generated by Django 4.2.7 on 2023-12-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_alter_teamgoals_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchSpecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialty", models.CharField(max_length=50)),
                ("brief_synopsis", models.CharField(max_length=200)),
                ("long_description", models.CharField(max_length=500)),
                ("icon", models.ImageField(upload_to="home/files/images")),
            ],
        ),
    ]
