# Generated by Django 4.2.7 on 2023-12-05 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0030_searchspecialty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchspecialty",
            options={"verbose_name_plural": "Search Specialties"},
        ),
    ]
