# Generated by Django 4.2.7 on 2023-12-20 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0031_alter_searchspecialty_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteinfo",
            name="mailing_address",
        ),
        migrations.AddField(
            model_name="siteinfo",
            name="city_state_zip",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="siteinfo",
            name="po_box",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="siteinfo",
            name="street_address",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
