# Generated by Django 4.2.7 on 2023-12-27 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0032_remove_siteinfo_mailing_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="about_photo_1",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="home/files/images"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="siteinfo",
            name="about_photo_2",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="home/files/images"
            ),
            preserve_default=False,
        ),
    ]
