# Generated by Django 4.2.7 on 2023-12-28 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0033_siteinfo_about_photo_1_siteinfo_about_photo_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="contact_photo_1",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="home/files/images"
            ),
            preserve_default=False,
        ),
    ]
