# Generated by Django 4.2.7 on 2023-12-30 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0034_siteinfo_contact_photo_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="contact_photo_2",
            field=models.ImageField(
                default=datetime.datetime(
                    2023, 12, 30, 12, 20, 42, 957130, tzinfo=datetime.timezone.utc
                ),
                upload_to="home/files/images",
            ),
            preserve_default=False,
        ),
    ]
