# Generated by Django 4.2.7 on 2024-01-06 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0036_siteinfo_about_photo_3"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="donate_photo_1",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="home/files/images"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="siteinfo",
            name="donate_photo_2",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="home/files/images"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="siteinfo",
            name="donate_photo_3",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="home/files/images"
            ),
            preserve_default=False,
        ),
    ]
