# Generated by Django 5.0.1 on 2024-02-08 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0037_siteinfo_donate_photo_1_siteinfo_donate_photo_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="blank_icon",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="home/files/images"
            ),
            preserve_default=False,
        ),
    ]
