# Generated by Django 5.0.1 on 2024-04-02 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_siteinfo_blank_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchspecialty',
            name='transparent_icon',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='home/files/images'),
            preserve_default=False,
        ),
    ]
