# Generated by Django 5.0.1 on 2024-04-03 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_searchspecialty_transparent_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchspecialty',
            name='specialty_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='home/files/images'),
            preserve_default=False,
        ),
    ]
