# Generated by Django 5.0.1 on 2024-04-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_searchspecialty_specialty_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchspecialty',
            name='long_description',
            field=models.TextField(max_length=800),
        ),
    ]
