# Generated by Django 5.0.1 on 2024-04-06 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_searchspecialty_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='mipsarc_logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='home/files/images'),
            preserve_default=False,
        ),
    ]
