# Generated by Django 5.0.6 on 2024-05-26 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_siteinfo_mipsarc_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchspecialty',
            name='long_description',
        ),
        migrations.AddField(
            model_name='searchspecialty',
            name='long_descript_part2',
            field=models.TextField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchspecialty',
            name='long_description_part1',
            field=models.TextField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
