# Generated by Django 5.0.6 on 2024-06-20 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_searchspecialty_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='donate_photo_4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='home/files/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='donate_photo_5',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='home/files/images'),
            preserve_default=False,
        ),
    ]
