# Generated by Django 5.0.6 on 2024-07-21 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_siteinfo_misar_services_1_siteinfo_misar_services_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='just_a_dog_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='home/files/images'),
            preserve_default=False,
        ),
    ]
