# Generated by Django 4.2.7 on 2023-11-25 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_alter_member_managers_remove_member_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="member_since",
        ),
        migrations.RemoveField(
            model_name="member",
            name="website_join_date",
        ),
    ]
