# Generated by Django 4.2.7 on 2023-11-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_member_website_join_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="website_join_date",
        ),
        migrations.AddField(
            model_name="member",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
