# Generated by Django 4.2.7 on 2023-11-26 11:46

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0006_remove_member_website_join_date_member_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="state",
            field=localflavor.us.models.USStateField(
                max_length=2, verbose_name="state"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="zip_code",
            field=localflavor.us.models.USZipCodeField(
                max_length=10, verbose_name="zip_code"
            ),
        ),
    ]
