# Generated by Django 4.2.7 on 2023-12-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0010_remove_member_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="member_password",
            field=models.BooleanField(default=True, verbose_name="MISAR Secret Phrase"),
            preserve_default=False,
        ),
    ]
