# Generated by Django 4.2.7 on 2023-12-04 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0012_alter_member_member_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MemberFile",
        ),
    ]
