# Generated by Django 4.2.7 on 2023-12-05 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0014_memberfile_filesharing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberfile",
            name="user",
        ),
    ]
