# Generated by Django 4.2.7 on 2023-12-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0015_remove_memberfile_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memberfile",
            options={},
        ),
        migrations.AddField(
            model_name="memberfile",
            name="file_name",
            field=models.CharField(
                default=models.FileField(upload_to="member_files/"), max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="memberfile",
            name="file",
            field=models.FileField(upload_to="member_files/"),
        ),
    ]
