# Generated by Django 4.2.7 on 2023-12-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0016_alter_memberfile_options_memberfile_file_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filesharing",
            name="recipient",
        ),
        migrations.AlterField(
            model_name="memberfile",
            name="file",
            field=models.FileField(upload_to="members/member_files/"),
        ),
        migrations.AlterField(
            model_name="memberfile",
            name="file_name",
            field=models.CharField(
                default=models.FileField(upload_to="members/member_files/"),
                max_length=50,
            ),
        ),
    ]
