# Generated by Django 4.2.7 on 2023-12-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0017_remove_filesharing_recipient_alter_memberfile_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberfile",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="memberfile",
            name="date_modified",
        ),
        migrations.AlterField(
            model_name="memberfile",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="members/member_files/"
            ),
        ),
        migrations.AlterField(
            model_name="memberfile",
            name="file_name",
            field=models.CharField(
                default=models.FileField(
                    blank=True, null=True, upload_to="members/member_files/"
                ),
                max_length=50,
            ),
        ),
    ]
