# Generated by Django 4.2.7 on 2023-12-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0018_remove_memberfile_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberfile",
            name="file_name",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="FileSharing",
        ),
    ]
