# Generated by Django 4.2.7 on 2023-12-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0019_alter_memberfile_file_name_delete_filesharing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberfile",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
    ]
