# Generated by Django 4.2.7 on 2023-12-06 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0020_alter_memberfile_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memberfile",
            options={
                "permissions": [
                    ("view_file", "Can view file"),
                    ("edit_file", "Can edit file"),
                    ("delete_file", "Can delete file"),
                    ("share_file", "Can share file"),
                    ("revoke_share", "Can revoke file sharing"),
                ]
            },
        ),
        migrations.AddField(
            model_name="memberfile",
            name="current_owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_files",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="memberfile",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="memberfile",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="memberfile",
            name="handle",
            field=models.SlugField(default="_test", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="memberfile",
            name="share_with_all",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="memberfile",
            name="users",
            field=models.ManyToManyField(
                related_name="owned_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="FileSharing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "Can view file"),
                            ("edit", "Can edit file"),
                            ("delete", "Can delete file"),
                            ("share", "Can share file"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_shared", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.memberfile",
                    ),
                ),
                (
                    "recipient",
                    models.ManyToManyField(
                        related_name="file_sharings", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileOwnershipTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_requested", models.DateTimeField(auto_now_add=True)),
                ("date_completed", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.memberfile",
                    ),
                ),
                (
                    "from_members",
                    models.ManyToManyField(
                        related_name="ownership_transfers_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_members",
                    models.ManyToManyField(
                        related_name="ownership_transfers_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
