# Generated by Django 4.2.7 on 2023-12-07 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0021_alter_memberfile_options_memberfile_current_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memberfile",
            old_name="date_modified",
            new_name="last_modified",
        ),
    ]
