# Generated by Django 4.2.7 on 2023-12-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0022_rename_date_modified_memberfile_last_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberfile",
            name="file",
            field=models.FileField(upload_to="media/"),
        ),
    ]
