# Generated by Django 4.2.7 on 2023-12-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0023_alter_memberfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberfile",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
