# Generated by Django 4.2.7 on 2023-12-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0025_alter_memberfile_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberfile",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
