# Generated by Django 4.2.7 on 2023-12-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0027_remove_memberfile_file_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="memberfile",
            name="permissions",
            field=models.ManyToManyField(related_name="files", to="members.permission"),
        ),
    ]
