# Generated by Django 4.2.7 on 2023-12-10 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0029_alter_memberfile_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memberfile",
            old_name="file_name",
            new_name="file_description",
        ),
    ]
