# Generated by Django 4.2.7 on 2023-12-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0030_rename_file_name_memberfile_file_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_password",
            field=models.CharField(
                help_text="Code Supplied by MISAR to allow Registration.",
                max_length=15,
                verbose_name="MISAR Secret Phrase",
            ),
        ),
    ]
