# Generated by Django 4.2.7 on 2023-12-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0031_alter_member_member_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_password",
            field=models.CharField(max_length=15, verbose_name="MISAR Secret Phrase"),
        ),
    ]
