# Generated by Django 4.2.7 on 2023-12-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0032_alter_member_member_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filesharing",
            name="permission",
        ),
        migrations.AlterField(
            model_name="permission",
            name="description",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name="filesharing",
            name="permission",
            field=models.ManyToManyField(to="members.permission"),
        ),
    ]
