# Generated by Django 4.2.7 on 2023-12-13 03:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0033_remove_filesharing_permission_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memberfile",
            options={
                "permissions": [
                    ("view", "Can view file"),
                    ("edit", "Can edit file"),
                    ("share", "Can share file"),
                    ("revoke_share", "Can revoke file sharing"),
                ]
            },
        ),
    ]
