# Generated by Django 4.2.7 on 2023-12-14 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0034_alter_memberfile_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filesharing",
            old_name="permission",
            new_name="permissions",
        ),
    ]
