# Generated by Django 4.2.7 on 2023-12-15 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0035_rename_permission_filesharing_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_shared", models.DateTimeField(auto_now_add=True)),
                ("can_share", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_download", models.BooleanField(default=False)),
                ("is_owner", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="filesharing",
            name="file",
        ),
        migrations.RemoveField(
            model_name="filesharing",
            name="permissions",
        ),
        migrations.RemoveField(
            model_name="filesharing",
            name="recipient",
        ),
        migrations.AlterModelOptions(
            name="memberfile",
            options={},
        ),
        migrations.RemoveField(
            model_name="memberfile",
            name="current_owner",
        ),
        migrations.RemoveField(
            model_name="memberfile",
            name="handle",
        ),
        migrations.RemoveField(
            model_name="memberfile",
            name="permissions",
        ),
        migrations.RemoveField(
            model_name="memberfile",
            name="users",
        ),
        migrations.AddField(
            model_name="memberfile",
            name="file_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="memberfile",
            name="slug",
            field=models.SlugField(
                default=django.utils.timezone.now,
                editable=False,
                max_length=56,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="FileOwnershipTransfer",
        ),
        migrations.DeleteModel(
            name="FileSharing",
        ),
        migrations.AddField(
            model_name="filepermission",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="members.memberfile"
            ),
        ),
        migrations.AddField(
            model_name="filepermission",
            name="permissions",
            field=models.ManyToManyField(to="members.permission"),
        ),
        migrations.AddField(
            model_name="filepermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="memberfile",
            name="shared_with",
            field=models.ManyToManyField(
                related_name="owned_by",
                through="members.FilePermission",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
