# Generated by Django 4.2.7 on 2023-12-15 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0036_filepermission_remove_filesharing_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberfile",
            name="owner",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_files",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
