# Generated by Django 4.2.7 on 2023-12-15 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0038_alter_memberfile_slug"),
    ]

    operations = []
