# Generated by Django 4.2.7 on 2023-12-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0039_auto_20231214_2209"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filepermission",
            name="can_delete",
        ),
        migrations.RemoveField(
            model_name="filepermission",
            name="permissions",
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
        migrations.AddField(
            model_name="filepermission",
            name="permissions",
            field=models.CharField(
                choices=[("view", "View"), ("edit", "Edit"), ("share", "Share")],
                default="view",
                max_length=20,
            ),
        ),
    ]
