# Generated by Django 4.2.7 on 2023-12-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0041_alter_filepermission_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filepermission",
            name="can_download",
        ),
        migrations.RemoveField(
            model_name="filepermission",
            name="can_edit",
        ),
        migrations.RemoveField(
            model_name="filepermission",
            name="can_share",
        ),
        migrations.RemoveField(
            model_name="filepermission",
            name="permissions",
        ),
        migrations.AddField(
            model_name="filepermission",
            name="permission",
            field=models.CharField(
                choices=[("V", "View"), ("S", "Share"), ("E", "Edit"), ("D", "Delete")],
                default="V",
                max_length=1,
            ),
        ),
    ]
