# Generated by Django 4.2.7 on 2023-12-17 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0043_alter_filepermission_permission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filepermission",
            old_name="permission",
            new_name="permissions",
        ),
        migrations.RenameField(
            model_name="filepermission",
            old_name="user",
            new_name="recipient",
        ),
    ]
