# Generated by Django 4.2.7 on 2023-12-20 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0046_alter_filepermission_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberfile",
            name="shared_with",
        ),
        migrations.DeleteModel(
            name="FilePermission",
        ),
    ]
