# Generated by Django 4.2.7 on 2023-12-20 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0047_remove_memberfile_shared_with_delete_filepermission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memberfile",
            options={"permissions": [("share_memberfile", "Can share member file")]},
        ),
    ]
