# Generated by Django 4.2.7 on 2023-12-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0048_alter_memberfile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberfile",
            name="file_description",
            field=models.CharField(max_length=50, verbose_name="File Description"),
        ),
        migrations.AlterField(
            model_name="memberfile",
            name="file_name",
            field=models.CharField(max_length=50, verbose_name="File Name"),
        ),
    ]
