# Generated by Django 4.2.7 on 2024-01-01 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0049_alter_memberfile_file_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_point_of_contact",
                    models.CharField(
                        max_length=50,
                        null=True,
                        verbose_name="Location Point of Contact, if exists.",
                    ),
                ),
                (
                    "location_phone_number",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Location Phone Number"
                    ),
                ),
                (
                    "location_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Location Email"
                    ),
                ),
                (
                    "location_name",
                    models.CharField(max_length=50, verbose_name="Location Name"),
                ),
                (
                    "location_website",
                    models.URLField(max_length=75, verbose_name="Location Website"),
                ),
                (
                    "location_description",
                    models.CharField(
                        max_length=50, verbose_name="Location Description"
                    ),
                ),
                (
                    "location_address",
                    models.CharField(max_length=100, verbose_name="Location Address"),
                ),
                (
                    "location_city",
                    models.CharField(max_length=50, verbose_name="Location City"),
                ),
                (
                    "location_state",
                    models.CharField(max_length=50, verbose_name="Location State"),
                ),
                (
                    "location_zip_code",
                    localflavor.us.models.USZipCodeField(
                        max_length=10, verbose_name="Location Zip Code"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(max_length=50, verbose_name="Event Name"),
                ),
                (
                    "description",
                    models.CharField(max_length=50, verbose_name="Event Description"),
                ),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="Event Type"),
                ),
                ("date", models.DateTimeField(verbose_name="Event Date")),
                (
                    "address",
                    models.CharField(max_length=50, verbose_name="Event Address"),
                ),
                ("city", models.CharField(max_length=50, verbose_name="Event City")),
                ("state", models.CharField(max_length=50, verbose_name="Event State")),
                (
                    "zip_code",
                    localflavor.us.models.USZipCodeField(
                        max_length=10, verbose_name="Event Zip Code"
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(auto_now_add=True)),
                (
                    "special_instructions",
                    models.TextField(
                        max_length=500, verbose_name="Special Instructions"
                    ),
                ),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="event_attendees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_organizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_poster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_location",
                        to="members.location",
                    ),
                ),
            ],
        ),
    ]
