# Generated by Django 4.2.7 on 2024-01-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0050_location_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="address",
        ),
        migrations.RemoveField(
            model_name="event",
            name="city",
        ),
        migrations.RemoveField(
            model_name="event",
            name="state",
        ),
        migrations.RemoveField(
            model_name="event",
            name="zip_code",
        ),
        migrations.AlterField(
            model_name="event",
            name="special_instructions",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Special Instructions"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="location_phone_number",
            field=models.CharField(
                blank=True,
                default=-5555,
                max_length=50,
                verbose_name="Location Phone Number",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="location_point_of_contact",
            field=models.CharField(
                blank=True,
                default="tim",
                max_length=50,
                verbose_name="Location Point of Contact, if exists.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="location_website",
            field=models.URLField(
                blank=True, max_length=75, verbose_name="Location Website"
            ),
        ),
    ]
