# Generated by Django 4.2.7 on 2024-01-01 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0051_remove_event_address_remove_event_city_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="location_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="location_city",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="location_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="location_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="location_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="location_phone_number",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="location_point_of_contact",
            new_name="point_of_contact",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="location_state",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="location_website",
            new_name="website",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="location_zip_code",
            new_name="zip_code",
        ),
    ]
