# Generated by Django 4.2.7 on 2024-01-01 12:35

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0052_rename_location_address_location_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_poster",
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_location",
                to="members.location",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(max_length=100, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(max_length=50, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="location",
            name="state",
            field=models.CharField(max_length=50, verbose_name="State"),
        ),
        migrations.AlterField(
            model_name="location",
            name="zip_code",
            field=localflavor.us.models.USZipCodeField(
                max_length=10, verbose_name="Zip Code"
            ),
        ),
    ]
