# Generated by Django 4.2.7 on 2024-01-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0053_remove_event_event_poster_alter_event_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(verbose_name="Event Date"),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.DateTimeField(blank=True, verbose_name="End Time"),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(verbose_name="Start Time"),
        ),
    ]
