# Generated by Django 5.0.1 on 2024-01-21 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0056_location_misar_poc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.TimeField(blank=True, verbose_name="End Time"),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.TimeField(verbose_name="Start Time"),
        ),
        migrations.AlterField(
            model_name="location",
            name="misar_poc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="misar_poc",
                to=settings.AUTH_USER_MODEL,
                verbose_name="MISAR Point of Contact",
            ),
        ),
    ]
