# Generated by Django 5.0.1 on 2024-01-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0057_alter_event_end_time_alter_event_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(verbose_name="Event Date"),
        ),
    ]
