# Generated by Django 5.0.1 on 2024-01-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0058_alter_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="End Time"),
        ),
    ]
