# Generated by Django 5.0.4 on 2024-05-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0061_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='event',
            name='last_modified',
        ),
        migrations.DeleteModel(
            name='EventMember',
        ),
    ]
