# Generated by Django 5.0.4 on 2024-05-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0062_remove_event_date_created_remove_event_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('edit_event', 'Can edit event')]},
        ),
    ]
