# Generated by Django 5.0.4 on 2024-05-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0066_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('can_view_event', 'Can view event'), ('can_change_event', 'Can change event'), ('can_delete_event', 'Can delete event'), ('can_add_event', 'Can share event')]},
        ),
    ]
