# Generated by Django 5.0.4 on 2024-05-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0067_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
