# Generated by Django 5.0.4 on 2024-05-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0068_alter_event_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('url', models.URLField(max_length=75, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'External Reference',
                'verbose_name_plural': 'External References',
            },
        ),
    ]
