# Generated by Django 5.0.6 on 2024-05-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0070_teamfilecategory_teamfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamfile',
            options={'verbose_name': 'team File', 'verbose_name_plural': 'team Files'},
        ),
        migrations.AlterModelOptions(
            name='teamfilecategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='teamfile',
            name='slug',
        ),
    ]
